services:
  sub1:
    build: ./sub1
    ports: ["8081:8080"]
    restart: unless-stopped

  sub2:
    build: ./sub2
    ports: ["8083:8080"]
    restart: unless-stopped

  powerline:
    build: ./powerline
    ports: ["8082:8080"]
    depends_on:
      - sub1
      - sub2
    restart: unless-stopped