version: '3.8'

services:
  sub1:
    build: ./sub1
    ports: ["8081:8080"]
    networks:
      - power-grid

  sub2:
    build: ./sub2
    ports: ["8083:8080"]
    networks:
      - power-grid

  powerline:
    build: ./powerline
    ports: ["8082:8080"]
    depends_on:
      - sub1
      - sub2
    networks:
      - power-grid

networks:
  power-grid:
    driver: bridge